"""
HVAC Fan — Export Trained Model to C++ Header
===============================================
Reads the trained K-Means centroids and scaler parameters,
and generates a C++ header file ready for the ESP32 firmware.

Also reads the validation thresholds to embed them in the header.

Usage:
    python export_to_c_header.py

Inputs:
    data/centroids.json
    data/scaler_params.json
    data/threshold_results.json

Outputs:
    data/model_params.h
"""

import os
import json
import numpy as np
from datetime import datetime

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")


def fmt_array(arr, per_line=4):
    """Format a float array as C initializer string."""
    items = [f"{v:.8f}f" for v in arr]
    lines = []
    for i in range(0, len(items), per_line):
        chunk = ", ".join(items[i : i + per_line])
        lines.append(f"        {chunk}")
    return ",\n".join(lines)


def main():
    print("=" * 60)
    print("  HVAC Fan — Export Model to C++ Header")
    print("=" * 60)

    # ─── Load Files ──────────────────────────────────────────────
    centroids_path = os.path.join(DATA_DIR, "centroids.json")
    scaler_path = os.path.join(DATA_DIR, "scaler_params.json")
    threshold_path = os.path.join(DATA_DIR, "threshold_results.json")

    for path, name in [
        (centroids_path, "centroids.json"),
        (scaler_path, "scaler_params.json"),
    ]:
        if not os.path.exists(path):
            print(f"\n[ERROR] {name} not found at {path}")
            print("  Run train_kmeans.py first.")
            return

    with open(centroids_path) as f:
        centroids_data = json.load(f)
    with open(scaler_path) as f:
        scaler_data = json.load(f)

    centroids = np.array(centroids_data["centroids"])
    n_clusters = centroids.shape[0]
    n_features = centroids.shape[1]
    feature_names = centroids_data.get("feature_names", [])

    mean = scaler_data["mean_"]
    scale = scaler_data["scale_"]

    # Load thresholds (optional — use defaults if not found)
    warn_thr = 0.45
    crit_thr = 0.72
    max_dist = 4.5

    if os.path.exists(threshold_path):
        with open(threshold_path) as f:
            thr_data = json.load(f)
        warn_thr = thr_data.get("warning_threshold", warn_thr)
        crit_thr = thr_data.get("critical_threshold", crit_thr)
        max_dist = thr_data.get("max_distance", max_dist)
        print(f"\n  Loaded thresholds from validation:")
        print(f"    WARNING  = {warn_thr}")
        print(f"    CRITICAL = {crit_thr}")
        print(f"    MAX_DIST = {max_dist}")
    else:
        print(f"\n  [INFO] threshold_results.json not found, using defaults.")

    # ─── Generate C++ Header ─────────────────────────────────────
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = f"""// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by: export_to_c_header.py
// Date: {timestamp}
// Project: HVAC Blower Fan Predictive Maintenance (CO326)
// ═══════════════════════════════════════════════════════════════

#pragma once

// ─── Model Dimensions ─────────────────────────────────────────
#define KMEANS_N_CLUSTERS   {n_clusters}
#define KMEANS_N_FEATURES   {n_features}

// ─── Anomaly Detection Thresholds ─────────────────────────────
// These were determined by validate_model.py threshold sweep.
// Score < WARN  → NORMAL  (green, fan runs)
// WARN ≤ Score < CRIT  → WARNING (yellow, alert sent)
// Score ≥ CRIT  → CRITICAL (red, auto-shutdown relay)
#define ANOMALY_WARN_THR    {warn_thr:.4f}f
#define ANOMALY_CRIT_THR    {crit_thr:.4f}f
#define MAX_EXPECTED_DIST   {max_dist:.4f}f

// ─── Anomaly Labels ──────────────────────────────────────────
#define LABEL_NORMAL    0
#define LABEL_WARNING   1
#define LABEL_CRITICAL  2

// ─── Feature Names (for reference) ───────────────────────────
// {', '.join(feature_names)}

// ─── StandardScaler Parameters ───────────────────────────────
// Applied as: scaled[i] = (raw[i] - SCALER_MEAN[i]) / SCALER_SCALE[i]
const float SCALER_MEAN[{n_features}] = {{
{fmt_array(mean)}
}};

const float SCALER_SCALE[{n_features}] = {{
{fmt_array(scale)}
}};

// ─── K-Means Centroids [{n_clusters} x {n_features}] ─────────
// Each row is a cluster centroid in scaled feature space.
// These represent the 3 "normal" operating modes of the fan.
const float KMEANS_CENTROIDS[{n_clusters}][{n_features}] = {{
"""

    for k in range(n_clusters):
        comment = f"  // Cluster {k}"
        if k == 0:
            comment += " — normal idle"
        elif k == 1:
            comment += " — normal load"
        elif k == 2:
            comment += " — normal high-speed"
        header += f"    {{{fmt_array(centroids[k]).strip()}}},{comment}\n"

    header += "};\n"

    # ─── Write File ──────────────────────────────────────────────
    output_path = os.path.join(DATA_DIR, "model_params.h")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"\n  Generated C++ header file:")
    print(f"  → {output_path}")
    print(f"  → {n_clusters} centroids × {n_features} features")
    print(f"  → {os.path.getsize(output_path)} bytes")

    # ─── Summary ─────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"  Export Complete!")
    print(f"{'='*60}")
    print(f"  Copy this file to your Stage 2 firmware:")
    print(f"  cp {output_path}")
    print(f"     → firmware/src/ml/model_params.h")
    print(f"{'='*60}\n")
    print("  ✅ Stage 1 is COMPLETE!")
    print("  You can now proceed to Stage 2 (ESP32 firmware + Docker stack).")


if __name__ == "__main__":
    main()
