// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by: export_to_c_header.py
// Date: 2026-04-24 13:18:31
// Project: HVAC Blower Fan Predictive Maintenance (CO326)
// ═══════════════════════════════════════════════════════════════

#pragma once

// ─── Model Dimensions ─────────────────────────────────────────
#define KMEANS_N_CLUSTERS 3
#define KMEANS_N_FEATURES 12

// ─── Anomaly Detection Thresholds ─────────────────────────────
// These were determined by validate_model.py threshold sweep.
// Score < WARN  → NORMAL  (green, fan runs)
// WARN ≤ Score < CRIT  → WARNING (yellow, alert sent)
// Score ≥ CRIT  → CRITICAL (red, auto-shutdown relay)
#define ANOMALY_WARN_THR 0.0100f // Raised for ESP32 (normal baseline ~0.005)
#define ANOMALY_CRIT_THR 0.0500f
#define MAX_EXPECTED_DIST 845.6086f

// ─── Anomaly Labels ──────────────────────────────────────────
#define LABEL_NORMAL 0
#define LABEL_WARNING 1
#define LABEL_CRITICAL 2

// ─── Feature Names (for reference) ───────────────────────────
// vib_rms, vib_peak, vib_crest, vib_kurt, cur_rms, cur_std, dom_freq, spec_rms,
// spec_cent, band1, band2, band3

// ─── StandardScaler Parameters ───────────────────────────────
// Applied as: scaled[i] = (raw[i] - SCALER_MEAN[i]) / SCALER_SCALE[i]
const float SCALER_MEAN[12] = {9.74199588f,  9.91985650f,  1.01824352f,
                               -0.81405253f, 3.92799163f,  0.04230893f,
                               34.93708982f, 1.09833660f,  27.93791101f,
                               11.13272844f, 13.01697490f, 50.22207831f};

const float SCALER_SCALE[12] = {0.02008099f, 0.14030444f,  0.01321625f,
                                1.55151911f, 0.00905633f,  0.01055837f,
                                1.10533462f, 0.51772108f,  1.09003090f,
                                5.36533307f, 11.72678771f, 24.18331292f};

// ─── K-Means Centroids [3 x 12] ─────────
// Each row is a cluster centroid in scaled feature space.
// These represent the 3 "normal" operating modes of the fan.
const float KMEANS_CENTROIDS[3][12] = {
    {1.10968323f, 0.64807297f, 0.52990722f, -0.11571123f, 1.00160239f,
     1.02180970f, 0.24467102f, 0.82178359f, 0.74288880f, 0.37844638f,
     0.27315865f, 0.62278297f}, // Cluster 0 — normal idle
    {-0.86683095f, -0.54919959f, -0.46060416f, 0.04477277f, -0.78190235f,
     -0.79663801f, -0.17317893f, -0.65907724f, -0.56537336f, -0.32867027f,
     -0.26550217f, -0.49830842f}, // Cluster 1 — normal load
    {1.47563898f, 20.62168530f, 22.17113025f, 20.82914752f, 1.10142273f,
     0.64560967f, -7.92991973f, 8.97700501f, -5.88244619f, 15.70452055f,
     24.34020043f, 6.26556787f}, // Cluster 2 — normal high-speed
};
